name: EasyQUIZ
main: kvetinac97\Main
api: ["2.0.0"]
load: STARTUP
description: "Easy quiz plugin for everyone!"
version: 2.0.1
author: kvetinac97
commands:
 eq:
  usage: "/eq"
  description: "Universal command for starting the quiz"
  permission: eq.command
 aw:
  usage: "/aw <num|answer>"
  description: "Universal command for answering the quiz"
  permission: eq.answer
permissions:
 eq:
  default: op
  description: "Top EasyQUIZ permission node"
  children:
   eq.command:
    default: op
    description: "You can start the quiz!"
   eq.answer:
    default: true
    description: "You can answer the quiz"
   eq.win:
    default: true
    description: "You are able to win!"
   eq.lose:
    default: op
    description: "You won't lose anything if you have lost!"