#Default config for v1.0.0

#Here, write your language: <= ENGLISH(en)
#Zde napište váš jazyk: <= ČEŠTINA(cs)
#Ici, écrivez votre langue: <= FRANÇAIS(fr)
#----------------------------- DEUTSCH (de)
#If you want add more languages, make a pull request on github!
language: "en"

#Version (1), don't change
version: 1

#Time that players have to answer each question (in seconds)
time_for_answer: 30

#Write, if you want to share stats like
#Answer: Yes Guessed: 20
show_stats: true

#Should be quiz e.g. started every X minutes after starting server?
#Write interval in minutes
auto_start: false
auto_interval: 10 

#Here, write max number of winners, unlimited for unlimited winners
#If there'll be more players who guessed correctly than limit, plugin
#will automatically pick limit (e.g. 5) winners
winners: 1
#Do you want to write names of winners? e.g. Winners: kvetinac97, shoghicp
#or just write: Winners: 2
#You needn't write this if you have show_stats on false
name_winners: true

#Commands that will be executed for players who answer correctly
#Write false if you don't want to execute any commands :3
# %PLAYER will be replaced with name of winner/loser
win_commands:
 - "say %PLAYER has won the quiz!"

#Commands that will be executed for players who answer wrongly
#Write false if you don't want to execute any commands
lose_commands: false